apiVersion: apps/v1
kind: Deployment
metadata:
  name: fukusound-postgres-deployment
  labels:
    app: fukusound
    ver: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fukusound
      ver: postgres-deployment
  template:
    metadata:
      labels:
        app: fukusound
        ver: postgres-deployment
    spec:
      containers:
        - name: fukusound-postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5324
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fukusound-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fukusound-postgres
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: fukusound-postgres
                  key: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdatavol
      volumes:
        - name: pgdatavol
          hostPath:
            path: /opt/fukusound/data
