apiVersion: v1
kind: Service
metadata:
  name: fukusound-postgres-service
  labels:
    app: fukusound
    ver: service
spec:
  selector:
    app: fukusound
    ver: postgres-deployment
  ports:
    - port: 5432
