name: deploy main
on:
  push:
    branches:
      - main
concurrency: production
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Use CLI
        uses: scaleway/action-scw@v0
        with:
          save_config: true
          export_config: true
          version: v2.13.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      - uses: actions/checkout@master
      - name: Login Scaleway Container Registry
        uses: docker/login-action@v2
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Build Docker image
        run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/handbuch:latest -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/handbuch:${{ github.sha }}
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/handbuch
          docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/handbuch:${{ github.sha }}
